# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/awsUtil.ipynb (unless otherwise specified).

__all__ = ['invokeLambdaWithApigatewayProxy']

# Cell
import json
import boto3
from pprint import pprint


def invokeLambdaWithApigatewayProxy(
    payload, function_name, region_name="ap-southeast-1", debug=False
):
    lambda_client = boto3.client("lambda", region_name=region_name)
    payload_json = json.dumps({"body": json.dumps(payload)})
    response = lambda_client.invoke(
        FunctionName=function_name,
        InvocationType="RequestResponse",  # RequestResponse waits for the response, Event is async
        Payload=payload_json.encode("utf-8"),
    )
    responsePayload = response["Payload"].read().decode("utf-8")
    try:
        result = json.loads(responsePayload)
        body = json.loads(result["body"])
        result["body"] = body
        if debug:
            pprint(responsePayload)
        return result
    except KeyError as e:
        print("there is a keyerror perhaps the function failed", e)
        print("result is")
        pprint(responsePayload)
        raise (e)
    except Exception as e:
        print("decoding failed", e)
        print(result)
        pprint(responsePayload)
        raise (e)