# AUTOGENERATED! DO NOT EDIT! File to edit: datetime.ipynb (unless otherwise specified).

__all__ = ['datestamp']

# Cell
from beartype import beartype

# Cell
from datetime import datetime, timezone
@beartype
def datestamp(dt:datetime = datetime.now())->int:
  dt = datetime.utcnow()
  datestamp = datetime(day=dt.day,month=dt.month,year=dt.year,tzinfo=timezone.utc).timestamp()
  return int(datestamp)