# AUTOGENERATED! DO NOT EDIT! File to edit: pdUtils.ipynb (unless otherwise specified).

__all__ = ['getDfHash']

# Cell
import pandas as pd
from hashlib import sha1

# Cell
def getDfHash(df:pd.DataFrame):
  df.to_feather('/tmp/feather')
  with open('/tmp/feather', 'rb') as f:
    objHash = sha1(f.read()).hexdigest()
  return objHash