# AUTOGENERATED! DO NOT EDIT! File to edit: schema.ipynb (unless otherwise specified).

__all__ = ['validateUrl']

# Cell
import jsonschema, requests
from types import SimpleNamespace

# Cell
def validateUrl(url,input_):
  schema = requests.get(url).json()
  res = jsonschema.validate(input_,schema)
  return SimpleNamespace(**input_)