# AUTOGENERATED! DO NOT EDIT! File to edit: secrets.ipynb (unless otherwise specified).

__all__ = ['getSecret']

# Cell
import boto3
import ujson as json

# Cell
def getSecret(name="removeBg", region='ap-southeast-1', **kwargs):
  session = boto3.session.Session()
  client = session.client(
      service_name='secretsmanager',
      region_name=region,
      **kwargs
  )
  get_secret_value_response = client.get_secret_value(
      SecretId=name
  )
  return json.loads(get_secret_value_response['SecretString'])