# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/string.ipynb (unless otherwise specified).

__all__ = ['urlDecode']

# Cell
def urlDecode(s:str)->dict:
    """Decode a url-encoded string into a dictionary of key/value pairs"""
    return dict([x.split('=') for x in s.split('&')])