name: Deploy to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Needed for proper versioning

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Extract version from tag and update settings.ini
        run: |
          # Extract version from tag (e.g., v0.0.121 -> 0.0.121)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Extracted version: $VERSION"

          # Update version in settings.ini
          sed -i "s/^version = .*/version = $VERSION/" settings.ini
          echo "Updated settings.ini with version $VERSION"
          cat settings.ini | grep version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          # Install project dependencies from settings.ini
          pip install requests boto3 ujson Pillow genson pyyaml dpath pytest beartype dataclasses-jsonschema cachetools pycryptodome

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
